### ISSUE TITLE
Show domainmodel of consumed services

### ISSUE THREAD

**Issue by jo2** [SeelabFhdo/AjiL#7]
It would be nice to have an overview over the entities a services has access to from consumed services. That way I wouldn´t have to recreate these entities if a new entitiy uses them.

**Comment by josor001** [comment]
Hi Jo,
thanks for your suggestion. Sounds feasible and like a good improvement for the tool. I'll promise to have a look into it next week :)!

**Comment by josor001** [comment]
Took a little hacking but a0b212 should do the trick. Note that the domain concepts are only copied once and no sync mechanism is running. For the future it'd be nice to use a different color for imported entities.
