### ISSUE TITLE
Several improvements for transformation from Seelabs DDD Profile

### ISSUE THREAD

**Issue by papltill** [SeelabFhdo/AjiL#9]
As discussed with Philip:
1. Entities should be able to posses other entities as attributes
2. Entities should be able to posses operations
3. Custom operations should be able to have a entity associated (the same way the CRUD operations can)

**Comment by josor001** [comment]
From today bachelor thesis supervision meeting:
for the next development iteration we will try to adress points 1 & 3. We decided against 2 because it would undermine AjiML's lightweight design.

Additionally we decided to change DataModelT type the attribute interchangeable

**Comment by josor001** [comment]
Well actually that'd be an issue for the generator or more specific its implementation, not for the modeling language :)

**Comment by josor001** [comment]
as promised, changes are integrated in the current dev branch. plz test and feedback :)
